export const functions = [
  "Accounting",
  "Administrative",
  "Arts and DesignBusiness",
  "Development",
  "Community and Social Services",
  "Consulting",
  "Education",
  "Engineering",
  "Entrepreneurship",
  "Healthcare Services",
  "Human Resources",
  "IT",
  "Legal",
  "Marketing",
  "Media and Communication",
  "Military and Protective Services",
  "Operations",
  "Product Management",
  "Program and Project Management",
  "Purchasing",
  "Quality Assurance",
  "Real Estate",
  "Research",
  "Sales",
  "Customer Success and Support",
  "N/A (Unemployed)",
];
export const seniorityList = [
  "Owner",
  "Partner",
  "CXO",
  "VP",
  "Director",
  "Manager",
  "Senior",
  "Entry",
  "Training",
  "Unpaid",
  "N/A (Unemployed)",
];
export const employmentTypes = [
  "Full Time",
  "Part Time",
  "Contact",
  "Prefer not to say",
];
export const salaryRangeList = [
  "£0-£9,999",
  "£10,000 - £24,999",
  "£25,000-£49,999",
  "£50,000 - £99,999",
  "£100,000+",
  "Prefer not to say",
];
export const numEmployeeList = ["0-9", "10-50", "51-250", "250+", "Unsure"];
export const businessTurnoverList = [
  "0-£249,999",
  "£250,000 - £999,999",
  "£1,000,000 - £4,999,999",
  "£5,000,000 - £24,999,999",
  "£25,000,000+",
  "Unsure",
];
